### PR TITLE
fixes sass --watch for mac osx maverick and other bits

### PR DESCRIPTION
**Pull request by mgan59**
Ran into several issues in customizing the theme using sass --watch  this patch contains the following adjustments.
- Updated instructions in Readme.md for setting up sass and fixing [mac osx maverick](http://stackoverflow.com/questions/22413834/getting-error-when-using-command-line-for-sass-to-watch-files)
  - Instructions include how to install bourbon in the correct path
- [Bourbon Deprecation box-shadow](https://github.com/thoughtbot/bourbon/issues/156) warnings issued during `sass --watch`
- `default.hbs` links to `screen.css` which doesn't reflect the correct changes from `sass --watch` instead use `uno.css`.  Curious if I'm missing something with `screen.css`?
- Add `.gitignore` so that we don't include `bourbon/bourbon` installation as this should always be handled by developer to ensure latest bourbon.

### CODE REVIEW

**Comment by mgan59** [comment]
This pull-request references my original issue #8

**Comment by vitorbrandao** [comment]
Hello @mgan59, thank you for this PR. Instructions for setting up sass and bourbon were valuable. 

I did apply these changes but I'm facing an error, any idea what is this about?:

```
$ cd ghost/content/themes/uno
$ sass --watch assets/scss:assets/css --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- rb-inotify (LoadError)
        from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:207:in `load_dependent_adapter'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:198:in `usable?'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:190:in `usable_and_works?'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:57:in `block in select_and_initialize'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:55:in `each'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:55:in `select_and_initialize'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:291:in `initialize_adapter'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:283:in `setup'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:65:in `start!'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/plugin/compiler.rb:291:in `listen_to'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/plugin/compiler.rb:257:in `watch'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/plugin.rb:108:in `method_missing'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/exec.rb:509:in `watch_or_update'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/exec.rb:346:in `process_result'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/exec.rb:43:in `parse'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/lib/sass/exec.rb:22:in `parse!'
        from /projects/.gem/ruby/2.0.0/gems/sass-3.3.4/bin/sass:13:in `<top (required)>'
        from /usr/local/bin/sass:23:in `load'
        from /usr/local/bin/sass:23:in `<main>'
```

**Comment by mgan59** [comment]
@noisebleed glad it has helped some though sorry you are stuck.  I'm not really a ruby person more of a python/javascript developer so my ability to trouble shoot ruby and the gem installer is limited.

I googled and found this github issues with the [rb-inotify having load issues](https://github.com/gitlabhq/gitlabhq/issues/1768) and there is a thread of people trying different things.  

Curious what's your environment?  mac osx? Also if mac are you on maverick and did you do an upgrade or a clean install?  There is another [thread](https://drupal.org/node/2148277) with what might be similar issues.  They discuss issues with maverick installs and I'm on a clean install with everything working properly.

**Comment by vitorbrandao** [comment]
Hi again @mgan59, I'm running Gentoo Linux.

`# gem install rb-inotify` fixed the problem for me. Yay! And thanks for the bourbon fix, I was in a dead end because of that.

**Comment by mgan59** [comment]
@noisebleed glad to hear everything is working. I'll add that to the readme as it may be an issue with other linux setups.

**Comment by daleanthony** [comment]
Awesome, thank for doing this :)

**Pull request merged**
